name: Swift Build & Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch: # Allows manual execution

jobs:
  build:
    runs-on: macos-latest # Use macOS runner for Swift

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up Swift
        run: swift --version # Verify Swift installation

      - name: Build Swift Project
        run: swift build -v # Compile Swift code

      - name: Run Tests
        run: swift test -v # Execute tests if available
